language: c
compiler:
  - gcc
script: make all -f makefile.mk
dist: xenial
addons:
  apt:
    sources:
      - github-git-lfs-xenial
      - ppa:git-core/ppa
before_install:
  - apt-get install check
  
            